<?php

/** @var $block \Magegro\OpeningsTime\Block\OpeningsTime */
?>
<div data-block="openings" data-bind="scope: 'openings_content'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->

    <script type="text/x-magento-init">
        {
        "[data-block='openings']": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "openings_content": {
                        "component": "Magegro_OpeningsTime/js/openingstime",
                        "template": "Magegro_OpeningsTime/openingstime/content",
                        "openingstimedata": <?php /* @escapeNotVerified */ echo json_encode($block->getWeekDaysTime()); ?>,
                        "timeformat": <?php /* @escapeNotVerified */ echo $block->getConfigTimeFormat(); ?>

                    }
                }
            }
        }
    }
</script>

</div>