<?php

/**
 * @var \Magegro\OpeningsTime\Block\OpeningsTime $block
 */
// echo $block->getWeekDaysTime();
?>
<?php $daytime = $block->getWeekDaysTime(); ?>
<div class="container demo-bg">

    <div class="business-hours">
        <h2 class="title">Opening Hours</h2>

            <?php foreach ($daytime as $index => $data) { ?>
<ul>
                <li><?php echo $data['day']; ?></li>
                <li><?php echo $data['time']['open']; ?></li>
                <li><?php echo $data['time']['close']; ?></li>

                </ul>

            <?php  } ?>
    </div>
</div>