<?php

/** @var $block \Hayyan\OpeningsTime\Block\OpeningsTime */
?>
<div data-block="openings" class="openings-wrapper" data-bind="scope: 'openings_content'">
    <a href="#" class="toggle-slide" data-bind="click:show">Opening
    </a>
</div>
<div class="openings-content-wrapper" data-bind="scope: 'openings_content'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->

    <script type="text/x-magento-init">
        {
        "[data-block='openings']": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "openings_content": {
                        "component": "Hayyan_OpeningsTime/js/openings-hours",
                        "template": "Hayyan_OpeningsTime/openings/content",
                        "openingstimedata": <?php /* @escapeNotVerified */ echo json_encode($block->getWeekDays()); ?>
                    }
                }
            }
        }
    }
</script>

</div>